FROM php:8.2-cli

RUN docker-php-ext-install pdo_mysql sockets

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . /var/www/html/

RUN composer install --no-dev --optimize-autoloader

CMD ["php", "bin/consume-alerts.php"]
